apiVersion: apps/v1
kind: Deployment
metadata:
   name: mydeploy
   labels:
      env: test
spec:
   replicas: 1
   selector:
      matchLabels:
          env: test
   template:
      metadata:
         labels:
           env: test
      spec:
         containers:
           - name: cont1
             image: nginx
             ports:
               - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
   name: mysvc
spec:
  ports:
     - protocol: TCP
       port: 80
       targetPort: 80
  selector:
     env: test
  type: ClusterIP
