apiVersion: apps/v1
kind: Deployment
metadata:
   name: mydeploy
   labels:
      env: test
spec:
   replicas: 1
   selector:
      matchLabels:
          env: test
   template:
      metadata:
          labels:
              env: test
     spec:
        containers:
           - name: c1
             image: rockylinux: 9
             command: ["sleep", "infinity"]
             env:
               - name: MY_ENV
                 valueFrom:
                    configMapKeyRef:
                        name: mymap
                        key: config.conf
                              
