apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod
  labels:
     env: prod
spec:
  replicas: 4
  selector:
    matchLabels:
       env: prod
    template:
       metadata:
         labels:
            env: prod
    spec:
      containers:
         - name: mypod1
           image: ubuntu
           command: ["/bin/bash" , "-c" , "while true; do echo hello; sleep 30; done"]
    strategy:
       type: RollingUpdate
       rollingUpdate:
          maxUnavailable: 2
