apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  labels:
    env: test
spec:
  replicas: 2
  selector:
     matchLabels:
        env: test
  template:
    metadata:
       labels:
          env: test
    spec:
     containers:
      - name: mypod
        image: nginx
        ports:
           - containerPort: 80

