apiVersion: v1
kind: Pod
metadata:
   name: myinit
spec:
  initContainers:
     - name: init
       image: rockylinux:9
       command: ["/bin/bash", "-c" , "echo hello shweta > /tmp/dev/file"]
       volumeMounts:
          - name: devops
            mountPath: /tmp/dev/
  containers:
     - name: mypod
       image: ubuntu
       command: ["/bin/bash" , "-c" , "while true; do cat /tmp/dev/file; sleep 30; done"]
       volumeMounts:
          - name: devops
            mountPath: /tmp/dev
  volumes:
     - name: devops
       emptyDir: {}
