apiVersion: batch/v1
kind: Job
metadata: 
  name: myjob1
spec:
  parallelism: 5
  completions: 5
  activeDeadlineSeconds: 60
  template:
     spec: 
       containers:
          - name: mycont
            image: ubuntu
            command: ["/bin/bash" , "-c" , "while true; do echo hello; sleep 10; done"]
       restartPolicy: Never
