apiVersion: apps/v1
kind: Deployment
metadata:
   name: mydeploy
   labels:
      test: class
spec:
   relicas: 1
   selector: 
      matchLabels:
         test: class
   template:
      metadata:
         labels:
            test: class
      spec:
         containers:
            - name: shweta1
              image: nginx
              ports:
                 - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
   name: mysvc
spec:
   ports:
     - protocol: TCP
       port: 80
       targetPort: 80
       nodePort: 30007
   selector:
       test: class
   type: NodePort

