apiVersion: v1
kind: ResourceQuota
metadata:
    name: compute-resource
    namespace: project
spec:
   hard:
       pods: "8"
       requests.cpu: "2"
       requests.memory: "4Gi"
       limits.cpu: "8"
       limits.memory: "8Gi"
