apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: myrs
   labels:
      env: test
      class: first
spec:
   replicas: 2
   selector:
      matchLabels:
          env: test
   template:
      metadata:
         labels:
           env: test
      spec:
         containers:
            - name: mypo
              image: nginx
