apiVersion: apps/v1
kind: Deployment
metadata:
    name: mydeploy
    labels:
       project: env
spec:
   replicas: 1
   selector:
     matchLabels:
       project: env
   template:
     metadata:
       project: env
     spec:
       containers:
         - name: c1
           image: ubuntu
           command: ["sleep" ,"infinity"]
           volumeMounts:
              - name: volsecret
                mountPath: "/tmp/file"
       volumes:
           - name: volsecret
             secret:
                secretName: secret

# secret create
# kubectl create secret generic <secret-name> --from-file=<filename>
# kubectl create secret generic mysecret  --from-file=password.txt
