apiVersion: v1
kind: Pod
metadata:
    name: pods
spec:
   containers:
      - name: mypod1
        image: ubuntu
        command: ["/bin/bash" , "-c" , "while true; do echo hello; sleep 10; done"]
      - name: mypod2
        image: nginx
        ports:
           - containerPort: 80
